apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-srv-account
  namespace: default
## Luego de crear el service account se crea el token
# kubectl create token [NOMBRE-SA]
# kubectl create token my-srv-account
---
apiVersion: v1
kind: Secret
metadata:
  name: my-srv-account-secret
  annotations:
    kubernetes.io/service-account.name: my-srv-account #el mismo de la linea 4
type: kubernetes.io/service-account-token
##
# ver el token 
# kubectl get secret/my-srv-account-secret -o yaml

# Para validar lo que tiene el secret
#kubectl describe secret/my-srv-account-secret

## --- usando la api de k8s desde un pod
# 1. entrar en el pod y validar el punto de montaje donde estan los secrets
# 2. tomar el token
#    TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
# 3. usar el siguiente curl --> ver mas opciones en k8s api docs el kubernetes depende del cluster
#    curl -H "Authorization: Bearer ${TOKEN}" https://kubernetes/api/v1 --insecure
#    curl -H "Authorization: Bearer ${TOKEN}" https://kubernetes/api/v1/namespaces/default/pods --insecure