apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: app
    image: polinux/stress
    resources:
      limits:
        memory: "512Mi"
        cpu: "200m"
      requests:
        memory: "126Mi"
        cpu: "100m"
    command: ["stress"]
    args: ["--vm","1","--vm-bytes","150M","--vm-hang","1"]