apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: busybox:latest
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5 
      periodSeconds: 5

# La explicacion del yaml indica que haremos un probe liveness tipo command
# kubelete ejecutara el cat sobre el archivo /tmp/healthy cada 5 segundos empezando en 5
# la linea 14 en los args lo que esta realizando es crear el archivo esperar 30 segundos,
# lo borra y espera 5 mins

# El comportamiento deseado será que al segundo 35 el liveness no vea el archivo por ende deberia fallar

# al levantarlo y esperar efectivamente si describo el pod saldra algo similar a esto:

#  Warning  Unhealthy  12s (x3 over 22s)  kubelet            Liveness probe failed: cat: can't open '/tmp/healthy': No such file or directory
#  Normal   Killing    12s                kubelet            Container liveness failed liveness probe, will be restarted


# Si no soluciono el problema el pod quedará marcado como backoff es decir que k8s intento e intento pero nunca pudo subir el pod