apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: opsdockerimage/e2e-test-images-agnhost:2.26
    args:
    - liveness
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 5

# La explicacion del yaml indica que haremos un probe liveness tipo http
# El cual correra cada 3 segundos esperando 5 segs para iniciar

# El comportamiento deseado será que falle ya que la imagen esta creada para que despues de 10 segundos coloque un 500 en la respuesta
# y se reinicie al describir el pod lo podemos ver

#  Warning  Unhealthy  4s (x3 over 14s)  kubelet            Liveness probe failed: HTTP probe failed with statuscode: 500
#  Normal   Killing    4s                kubelet            Container liveness failed liveness probe, will be restarted
#  Normal   Started    3s (x2 over 28s)  kubelet            Started container liveness


# Si no soluciono el problema el pod quedará marcado como backoff es decir que k8s intento e intento pero nunca pudo subir el pod