apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-l2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/test"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Validar siempre que consumamos el total del pv ya que ningun otro lo podrá usar

#como en este manifiesto no hay definido el PV entonces k8s busca un PV que se pueda usar con el tamaño
#k8s get pvc -o wide
#NAME            STATUS   VOLUME      CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE   VOLUMEMODE
#task-pv-claim   Bound    pv-volume-l2   10Gi       RWO            manual         <unset>                 13s   Filesystem
