apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-vars
  labels:
    app: front
  namespace: test
data:
  script: |
    echo "Hola Devops" > /usr/share/nginx/html/test.html

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx-vars
  namespace: test
  labels:
    app: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata: 
      labels:
        app: front
    spec:
      containers:
        - name: nginx-container
          image: nginx:alpine
          volumeMounts:
          - name: scripts-vol
            mountPath: /etc/nginx/conf.d/
      volumes:
        - name: scripts-vol
          configMap:
            name: nginx-vars
            items:
              - key: script
                path: demo-script.sh          
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: front
  namespace: test
spec:
  type: ClusterIP
  selector:
    app: front 
  ports:
  - name: nginx-service-port
    protocol: TCP
    port: 8080 #El puerto con el que escuchara el servicio
    targetPort: 80