#lab1 crear un secreto usando data (con info ya en base64)
apiVersion: v1
kind: Secret
metadata:
  name: secret-data
#type: kubernetes.io/basic-auth
type: Opaque
data:
  username: ZGJfdXNlcl9hcHAK # required field for kubernetes.io/basic-auth
  password: JSZhZHMxMjMK # required field for kubernetes.io/basic-auth