#lab3 crear un secreto usando variables de entorno
apiVersion: v1
kind: Secret
metadata:
  name: secret-data
#type: kubernetes.io/basic-auth
type: Opaque
data:
  username: $USER #Aqui k8s no llo toma como var de entorno de shell, sino lo toma de forma literal
  password: $PASSWORD #Aqui k8s no llo toma como var de entorno de shell, sino lo toma de forma literal

#con esta forma y haciendo uso de la herramienta envsubst podemos guardar el archivo de configuracion
# hacer el reemplazo en ejecución y aplicar es sobre la salida del envsubst 