#lab1 crear un secreto usando data (con info ya en base64)
apiVersion: v1
kind: Secret
metadata:
  name: secret-data
#type: kubernetes.io/basic-auth
type: Opaque
data:
  USERNAME: ZGJfdXNlcl9hcHAK # required field for kubernetes.io/basic-auth
  PASSWORD: JSZhZHMxMjMK # required field for kubernetes.io/basic-auth
---
#lab5 inyectar secretos al pod como volumen y variables de ambiente
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret-as-volume
spec:
  containers:
  - name: podsito
    image: nginx:alpine
    env:
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secret-data
            key: PASSWORD
    volumeMounts:
    - name: secret-path
      mountPath: "/etc/nginx/conf.d/secret-data"
      readOnly: true
  volumes:
  - name: secret-path
    secret:
      secretName: secret-data
      items:
        - key: USERNAME
          path: user.txt
        
      #crearle los items para que no se creen archivos llamados username y password
      #que son lcomo las keys del secret y de contenido el value