apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: app
    image: polinux/stress
    resources:
      limits:
        memory: "512Mi"
        cpu: "200m"
      requests:
        memory: "126Mi"
        cpu: "100m"
    command: ["stress"]
    args: ["--vm","1","--vm-bytes","1000G","--vm-hang","1"]

    # la idea era hacer que el pod pidiera una memoria que ni los runners pudieran correra para mostrarnos 
    # el error que nos mostraria
    # ejecutamos el kubectl apply -f limits.yaml y miramos la consola 
#    Events:
#       Type     Reason     Age                    From               Message
#       ----     ------     ----                   ----               -------
#       Normal   Scheduled  3m45s                  default-scheduler  Successfully assigned default/frontend to minikube
#       Normal   Pulled     3m44s                  kubelet            Successfully pulled image "polinux/stress" in 757ms (757ms including waiting). Image size: 9744175 bytes.
#       Normal   Pulled     3m41s                  kubelet            Successfully pulled image "polinux/stress" in 732ms (732ms including waiting). Image size: 9744175 bytes.
#       Normal   Pulled     3m26s                  kubelet            Successfully pulled image "polinux/stress" in 724ms (724ms including waiting). Image size: 9744175 bytes.
#       Normal   Created    2m54s (x4 over 3m44s)  kubelet            Created container app
#       Normal   Started    2m54s (x4 over 3m44s)  kubelet            Started container app
#       Normal   Pulled     2m54s                  kubelet            Successfully pulled image "polinux/stress" in 834ms (834ms including waiting). Image size: 9744175 bytes.
#       Warning  BackOff    2m24s (x7 over 3m40s)  kubelet            Back-off restarting failed container app in pod frontend_default(c10c00a6-601a-4693-addb-1a272574672b)
#       Normal   Pulling    2m11s (x5 over 3m45s)  kubelet            Pulling image "polinux/stress"
#       Normal   Pulled     2m10s                  kubelet            Successfully pulled image "polinux/stress" in 820ms (820ms including waiting). Image size: 9744175 bytes.