apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: app
    image: polinux/stress
    resources:
      limits:
        memory: "512Mi"
        cpu: "200m"
      requests:
        memory: "126Mi"
        cpu: "100m"
    command: ["stress"]
    args: ["--vm","1","--vm-bytes","680M","--vm-hang","1"]

    # la idea era hacer que el pod pidiera mas memoria para mostrarnos el error que nos mostraria y una forma de verlo
    # ejecutamos el kubectl appply -f limits.yaml y miramos la consola 
#   kubectl apply -f limits.yaml; kubectl get pods --watch
#     pod/frontend created
#     NAME       READY   STATUS              RESTARTS   AGE
#     frontend   0/1     ContainerCreating   0          1s
#     frontend   1/1     Running             0          2s
#     frontend   0/1     OOMKilled           0          3s
#     frontend   1/1     Running             1 (1s ago)   4s
#     frontend   0/1     OOMKilled           1 (3s ago)   6s
#     frontend   0/1     CrashLoopBackOff    1 (16s ago)   21s
#     frontend   1/1     Running             2 (17s ago)   22s
#     frontend   0/1     OOMKilled           2 (18s ago)   23s