apiVersion: v1
kind: Namespace
metadata:
  name: limited
  labels:
    app: backend

---    
apiVersion: v1
kind: ResourceQuota
metadata:
  name: res-limited-quota-demo
  namespace: limited
spec:
  hard:
    pods: "3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: limited-test
  namespace: limited
  labels:
    app: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80