apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-group
rules:
- apiGroups: [""] #validar con k8s api-resources los apiGroups
  resources: ["services"]
  verbs: ["*" ]
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-users-to-services
subjects:
- kind: Group
  name: dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: dev-group
  apiGroup: rbac.authorization.k8s.io