apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-selec-pod
  labels:
    mysql: ready
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-selec-pod
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Validar siempre que consumamos el total del pv ya que ningun otro lo podrá usar
  selector: #con estas sentencias le digo al PVC cual es el PV que debe tomar es decir el que tenga la 
            # label mysql: ready
    matchLabels: 
      mysql: ready
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-selec-pv-mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123456789"
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mysql-data-vol
#de aqui en adelante montaremos el PV al pod
      volumes:
        - name: mysql-data-vol
          persistentVolumeClaim:
            claimName: pvc-selec-pod