apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-vars
  labels:
    app: front
data:
  DB_HOST: dev.host.local
  DB_USER: dev_user
  script: |
    echo "DB host es " $HOST" y DB_USER es "$USER > /usr/share/nginx/html/test.html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  labels:
    app: front
data:
  nginx: |
    server {
      listen       8080;
      server_name  localhost;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx-vars
  labels:
    app: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata: 
      labels:
        app: front
    spec:
      containers:
        - name: nginx-vars-container
          image: nginx:alpine
          env:
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: nginx-vars
                key: DB_HOST
          - name: USER
            valueFrom:
              configMapKeyRef:
                name: nginx-vars
                key: DB_USER
          volumeMounts:
          - name: nginx-vol
            mountPath: /etc/nginx/conf.d/
            #readOnly: true
          - name: scripts-vol
            mountPath: /opt/nginx-scripts/
            #readOnly: true
      volumes:
        - name: nginx-vol
          configMap:
            name: nginx-conf
            #items: # sino defino los items el escribira todas las llaves que esten configuradas en el configMap y los nombres de los archivos seran los mismos keys
            #- key: nginx   # viene de la configuracion del configMapa en la parte data (nginx y test)
            #  path: default.conf # nombre del archivo una vez se inicie en el server
        - name: scripts-vol
          configMap:
            name: nginx-vars
            items:
              - key: script
                path: demo-script.sh