apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo2
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "1" 
      requests:
        cpu: "1"
    args:
    - -cpus
    - "1" 

#   kubectl describe pod cpu-demo2
#   Name:             cpu-demo2
#   Namespace:        default
#   Priority:         0
#   Service Account:  default
#   Node:             <none>
#   Labels:           <none>
#   Annotations:      <none>
#   Status:           Pending
#   IP:               
#   IPs:              <none>
#   Containers:
#     cpu-demo-ctr:
#       Image:      vish/stress
#       Port:       <none>
#       Host Port:  <none>
#       Args:
#         -cpus
#         2
#       Limits:
#         cpu:  1k
#       Requests:
#         cpu:        100
#       Environment:  <none>
#       Mounts:
#         /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-kdcgf (ro)
#   Conditions:
#     Type           Status
#     PodScheduled   False 
#   Volumes:
#     kube-api-access-kdcgf:
#       Type:                    Projected (a volume that contains injected data from multiple sources)
#       TokenExpirationSeconds:  3607
#       ConfigMapName:           kube-root-ca.crt
#       ConfigMapOptional:       <nil>
#       DownwardAPI:             true
#   QoS Class:                   Burstable
#   Node-Selectors:              <none>
#   Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
#                                node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
#   Events:
#     Type     Reason            Age                 From               Message
#     ----     ------            ----                ----               -------
#     Warning  FailedScheduling  13m (x14 over 78m)  default-scheduler  0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.




#QoS de k8s

# pod guarrented cuando limits y request son iguales
# pod bustable cuando limits es mayor del request
# pod besteffort cuando no se tienen definidos limits y request
